import type { ProviderDefinition } from '../types/index.js';

/**
 * Registry of all supported AI providers
 */
export const PROVIDERS: ProviderDefinition[] = [
  {
    id: 'anthropic',
    name: 'Anthropic (Native)',
    description: 'Use your existing Claude CLI configuration',
    color: '#D4A574',
    useExistingConfig: true,
    envVars: [],
  },
  {
    id: 'zai',
    name: 'Z.AI (GLM Models)',
    description: 'Cheaper alternative using GLM-4.7 models',
    color: '#4A90D9',
    envVars: [
      {
        name: 'ANTHROPIC_AUTH_TOKEN',
        label: 'Z.AI API Key',
        description: 'Your Z.AI authentication token from z.ai/manage-apikey',
        type: 'apiKey',
        sensitive: true,
        required: true,
      },
      {
        name: 'ANTHROPIC_BASE_URL',
        label: 'Base URL',
        description: 'Z.AI API endpoint',
        type: 'url',
        sensitive: false,
        default: 'https://api.z.ai/api/anthropic',
        required: true,
      },
      {
        name: 'API_TIMEOUT_MS',
        label: 'Timeout (ms)',
        description: 'API request timeout in milliseconds',
        type: 'number',
        sensitive: false,
        default: 3000000,
        required: false,
      },
      {
        name: 'ANTHROPIC_DEFAULT_SONNET_MODEL',
        label: 'Sonnet Model',
        description: 'Model for Sonnet requests',
        type: 'string',
        sensitive: false,
        default: 'glm-4.7',
        required: false,
      },
      {
        name: 'ANTHROPIC_DEFAULT_OPUS_MODEL',
        label: 'Opus Model',
        description: 'Model for Opus requests',
        type: 'string',
        sensitive: false,
        default: 'glm-4.7',
        required: false,
      },
      {
        name: 'ANTHROPIC_DEFAULT_HAIKU_MODEL',
        label: 'Haiku Model',
        description: 'Model for Haiku requests',
        type: 'string',
        sensitive: false,
        default: 'glm-4.5-air',
        required: false,
      },
    ],
  },
  {
    id: 'openrouter',
    name: 'OpenRouter',
    description: 'Access 320+ models through OpenRouter',
    color: '#6366F1',
    envVars: [
      {
        name: 'OPENROUTER_API_KEY',
        label: 'OpenRouter API Key',
        description: 'Your OpenRouter API key',
        type: 'apiKey',
        sensitive: true,
        required: true,
      },
      {
        name: 'ANTHROPIC_API_KEY',
        label: 'Anthropic Key Override',
        description: 'Must be empty for OpenRouter to work',
        type: 'string',
        sensitive: false,
        default: '',
        required: true,
      },
      {
        name: 'ANTHROPIC_BASE_URL',
        label: 'Base URL',
        description: 'OpenRouter API endpoint',
        type: 'url',
        sensitive: false,
        default: 'https://openrouter.ai/api',
        required: true,
      },
      {
        name: 'ANTHROPIC_DEFAULT_SONNET_MODEL',
        label: 'Model Name',
        description: 'Model to use (e.g., openai/gpt-4o, anthropic/claude-3.5-sonnet)',
        type: 'string',
        sensitive: false,
        required: true,
      },
    ],
  },
  {
    id: 'moonshot',
    name: 'Kimi K2 (Moonshot AI)',
    description: '90% cheaper - Moonshot AI Kimi K2 models',
    color: '#10B981',
    envVars: [
      {
        name: 'ANTHROPIC_AUTH_TOKEN',
        label: 'Moonshot API Key',
        description: 'Your Moonshot AI API key from platform.moonshot.ai',
        type: 'apiKey',
        sensitive: true,
        required: true,
      },
      {
        name: 'ANTHROPIC_BASE_URL',
        label: 'Base URL',
        description: 'Moonshot API endpoint',
        type: 'url',
        sensitive: false,
        default: 'https://api.moonshot.ai/anthropic',
        required: true,
      },
      {
        name: 'ANTHROPIC_DEFAULT_SONNET_MODEL',
        label: 'Sonnet Model',
        description: 'Model for Sonnet requests',
        type: 'string',
        sensitive: false,
        default: 'kimi-k2-0711-preview',
        required: false,
      },
      {
        name: 'ANTHROPIC_DEFAULT_OPUS_MODEL',
        label: 'Opus Model',
        description: 'Model for Opus requests',
        type: 'string',
        sensitive: false,
        default: 'kimi-k2-0711-preview',
        required: false,
      },
    ],
  },
  {
    id: 'novita',
    name: 'Novita AI',
    description: 'Novita AI provider',
    color: '#F59E0B',
    envVars: [
      {
        name: 'ANTHROPIC_AUTH_TOKEN',
        label: 'Novita API Key',
        description: 'Your Novita AI API key',
        type: 'apiKey',
        sensitive: true,
        required: true,
      },
      {
        name: 'ANTHROPIC_BASE_URL',
        label: 'Base URL',
        description: 'Novita API endpoint',
        type: 'url',
        sensitive: false,
        default: 'https://api.novita.ai/anthropic',
        required: true,
      },
      {
        name: 'ANTHROPIC_MODEL',
        label: 'Model Override',
        description: 'Specific model to use (optional)',
        type: 'string',
        sensitive: false,
        required: false,
      },
    ],
  },
  {
    id: 'custom',
    name: 'Custom / Self-hosted',
    description: 'LiteLLM, Hugging Face TGI, or other compatible endpoints',
    color: '#8B5CF6',
    envVars: [
      {
        name: 'ANTHROPIC_BASE_URL',
        label: 'Base URL',
        description: 'Your custom API endpoint URL',
        type: 'url',
        sensitive: false,
        required: true,
      },
      {
        name: 'ANTHROPIC_AUTH_TOKEN',
        label: 'Auth Token',
        description: 'Authentication token (if required)',
        type: 'apiKey',
        sensitive: true,
        required: false,
      },
      {
        name: 'ANTHROPIC_API_KEY',
        label: 'API Key',
        description: 'API key (if required instead of token)',
        type: 'apiKey',
        sensitive: true,
        required: false,
      },
      {
        name: 'ANTHROPIC_MODEL',
        label: 'Model',
        description: 'Model identifier (optional)',
        type: 'string',
        sensitive: false,
        required: false,
      },
    ],
  },
];

/**
 * Get a provider by its ID
 */
export function getProviderById(id: string): ProviderDefinition | undefined {
  return PROVIDERS.find((p) => p.id === id);
}
